language: python
python:
- '3.5'
- '3.6'
- '3.7'
before_install:
- openssl aes-256-cbc -K $encrypted_94d8fbd70a3e_key -iv $encrypted_94d8fbd70a3e_iv -in tests/parameters.py.enc -out tests/parameters.py -d
install:
- "./scripts/travis_install.sh"
script:
- pytest --tb=native --cov-report xml --cov=snowflake.ingest tests
after_success:
- pip install codecov
- codecov -f snowflake-ingest-python-coverage.xml -t 661d6c83-f010-4af1-bf7f-0df1ce3dbc8d